-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 11:18:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- (Raquel) Añadido y conecta a la base de datos
ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weriumGames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProMotion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ProMotion`;

-- -----------------------------------------------------
-- Table `ProMotion`.`tabla_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProMotion`.`tabla_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_usuario_1` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_usuario_2` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weriumGames`.`tabla_sesiones`    (CONFIGURACIONES) 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProMotion`.`tabla_sesiones` (     
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `caso_estudio` VARCHAR(45) NULL DEFAULT NULL,
  `articulacion` VARCHAR(45) NULL DEFAULT NULL,
  `numero_sensores` VARCHAR(45) NULL DEFAULT NULL,
  `sensor1` VARCHAR(45) NULL DEFAULT NULL,
  `sensor2` VARCHAR(45) NULL DEFAULT NULL,
  `ROM_flexion` VARCHAR(45) NULL DEFAULT NULL,
  `ROM_extension` VARCHAR(45) NULL DEFAULT NULL,
  `ROM_inclinacion_izq` VARCHAR(45) NULL DEFAULT NULL,
  `ROM_inclinacion_der` VARCHAR(45) NULL DEFAULT NULL,
  `ROM_rotacion_izq` VARCHAR(45) NULL DEFAULT NULL,
  `ROM_rotacion_der` VARCHAR(45) NULL DEFAULT NULL,
  `comentarios` VARCHAR(300) NULL DEFAULT NULL,
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `ProMotion`.`tabla_datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProMotion`.`tabla_datos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_sesion` VARCHAR(45) NULL DEFAULT NULL,
  `Date` BIGINT NULL DEFAULT NULL,
  `movimiento` VARCHAR(45) NULL DEFAULT NULL,
  `alfa` VARCHAR(45) NULL DEFAULT NULL,
  `beta` VARCHAR(45) NULL DEFAULT NULL,
  `gamma` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
